### ISSUE TITLE
MIL VAD question

### ISSUE THREAD

**Issue by gitcheol** [fjchange/awesome-video-anomaly-detection#1]
Hi. Thanks to you, i could research the anomaly detection easily!

I have some question while studying.
1. I know the MIL refer the "Sultani_Real-World_Anomaly_Detection_CVPR_2018_paper" paper code but what is the VAD?? 

if above question is correct,
2. how did you get the MIL VAD results by using shanghaiTech data set? because this data set does not have the enough training data set,, (only training data has normal video) 
(MIL VAD	CVPR 18	Weakly (Re-Organized Dataset)	I3D-RGB	X	86.3	0.15)

Have a wonderful day. 
Thank you

**Comment by fjchange** [comment]
1. VAD is abbreviation of Video Anomaly Detection. I would update all this kind abbreviation to the popular way. Sorry about that.
2. MIL_VAD performance of ShanghaiTech is reported on  AR-Net, ICME 2020. Emm, I would update it too.

Thanks for your bug catching.

**Comment by fjchange** [comment]
I have updated the file recently. You can open a new issue if any questions.
