### ISSUE TITLE
10-crop and its lable : 关于10-crop提取特征的方式，它的label怎么获得

### ISSUE THREAD

**Issue by Apollo-asleep** [fjchange/awesome-video-anomaly-detection#11]
请问常用的10-crop-I3D特征提取方式，他们的10-crop的lable怎么获得呀。
比如一个异常视频320帧，分为32个instance，每个instance的lable怎么获得。（如果是正常视频，那么32个instance的lable都是0）

The commonly used 10-crop-i3d feature extraction methods and how to obtain their 10 Crop label.
For example, 320 frames of an abnormal video are divided into 32 instances. How can the label of each instance be obtained. (if it is a normal video, the label of 32 instances is 0)

**Comment by Ironieser** [comment]
现在papar都在着力解决的你所说的这个问题..

**Comment by Apollo-asleep** [comment]
请问没有instance_lable的情况下在inference阶段，大家一般怎么算AUC呢。
个人想法：
最科学的算法是知道每个instance的label，model对每个intance输出socre，计算AUC。
看到一个开源（RTFM）的做法是，一个视频的所有instance算出score求平均，作为整个视频的score，再和视频级别label算AUC。不过他开源里面还有个（*16）的操作没看懂。（https://github.com/tianyu0207/RTFM/issues/65），这种方法就要求输入的异常视频不能正常instance占多数，不然平均之后异常分数就低了。
未开源论文好像没有很说明inference阶段AUC的计算方式，大部分给出异常score的计算方式就结束了。
请问还有其他的AUC计算方式吗？
感谢阅读

**Comment by fjchange** [comment]
@Apollo-asleep 你所指出的RTFM是通过通过instance->clip->frame的方法，转换成frame级别的预测。分别对应这instance->instance所包含的clip->clip*16成对应的帧。所以最终还是按照帧级别计算AUC。

**Comment by Apollo-asleep** [comment]
Great!
