### ISSUE TITLE
Result Value Error 

### ISSUE THREAD

**Issue by gitcheol** [fjchange/awesome-video-anomaly-detection#2]
Hi Thank you for your last question answer! 
I found the some error. 

Sultani.etl | ICME 2020 | Weakly (Re-Organized Dataset) | I3D-RGB | X | 86.3 | 0.15

At the feature column, The AR-Net author who tested the Sultani.etl Shanghai dataset used the only C3D features to train& test the AUC! 

This is the part of the paper : 
WEAKLY SUPERVISED VIDEO ANOMALY DETECTION VIA CENTER-GUIDED DISCRIMINATIVE LEARNING
"
In order to present a comparison against MIL-based works on ShanghaiTech, we reproduced the method in [9] and adopted the open source code provided by Sultani et al. [7] to conduct the anomaly detection. The above two models are obtained by pretrained **C3D**. 
"

And really thank you for your persistent updates of README.md! 
Have a wonderful day!

**Comment by fjchange** [comment]
Oh, this is a mistake. Thanks for pointing out that. I have fixed it.
