### ISSUE TITLE
What is the definition of "end-to-end" in the table?

### ISSUE THREAD

**Issue by ascetic-monk** [fjchange/awesome-video-anomaly-detection#9]
First, thanks for your work, it really help me to better understand the development of VAD in recent year. I encount a question so I want to consult with you.
I note that you mark the "GCN-anomaly"(Zhong 2019) method as "end-to-end". However, in the github provided, I found that extracted features were utilized. And the training process contains 2 stages: generation of persudo labels and training of GCN structure. I wonder why the method is belong to "end-to-end" but the others( like the newest RTFM, which is the last line in table) does not.

**Comment by fjchange** [comment]
GCN-anomaly is to finetune the feature encoder. GCN is a tool to lower the label noise in the generated pseudo labels for better finetuning. The released codes are described the label noise cleaning process. 

Note that, the "End-to-End" in this repo means the model have only one step in the testing time rather than training time. 
It maybe misleading. I will modify it as MIST (CVPR 2021) mention, "Encoder-Agnostic" and "Encoder-based".

**Comment by ascetic-monk** [comment]
> GCN-anomaly is to finetune the feature encoder. GCN is a tool to lower the label noise in the generated pseudo labels for better finetuning. The released codes are described the label noise cleaning process.
> 
> Note that, the "End-to-End" in this repo means the model have only one step in the testing time rather than training time.
> It maybe misleading. I will modify it as MIST (CVPR 2021) mention, "Encoder-Agnostic" and "Encoder-based".

Thanks for answering! So can I explain the "end-to-end" in the other way: in Sultani, after feeding the features into the network, we still need to repeat the output 16 times to recover the time resolution during testing. However in the GCN-anomaly or MIST, we can get the anomaly score which has the same resolution as input video so no other operation is need. It is similar to the "coarse and fine grained" in MIST(2021).

**Comment by fjchange** [comment]
Encoder-based and Encoder-agnostic are related to training the feature encoder or not. Those marked with "end-to-end" it this repo before modifying are one-stage model in testing.

Coarse-grained and fine-grained are related to the prediction resolution, which are marked in the table as "32-segment" , which is the way Sulanti did.

**Comment by ascetic-monk** [comment]
> Encoder-based and Encoder-agnostic are related to training the feature encoder or not. Those marked with "end-to-end" it this repo before modifying are one-stage model in testing.
> 
> Coarse-grained and fine-grained are related to the prediction resolution, which are marked in the table as "32-segment" , which is the way Sulanti did.

OK, it is clear, thanks for answering.
